### ISSUE TITLE
Update content stage 1

### ISSUE THREAD

**Issue by matthijsgroen** [speedlazer/speedlazer#113]
This is about the overall content, not the 2 bossfights (they have their own issues here)

**Coming update**
- [x] Update Dialog helicopter attack
- [x] Draw parachute
- [x] Animate parachute ejecting from helicopter
- [ ] Draw/design "takeover" drone #90 
- [x] Draw "low" ship cabins to extend how 'Drone Ships' work
- [x] Update moving along bezier path to make it fluent #115 
- [x] Extend/cleanup test new particle system #108 
- [x] Finalize midstage boss #99 
- [x] Destroy hatches and cabin on mid-boss DroneShip 

**Next update**
- [ ] Finalize endstage boss #92

**Comment by matthijsgroen** [comment]
Old and obsolete, all content is currently remade
