### ISSUE TITLE
Update Stage 1 end-boss

### ISSUE THREAD

**Issue by matthijsgroen** [speedlazer/speedlazer#92]
Full list of attacks I want:

**Stage 1** (#87)

- [x] Rocket dance
- [x] Homing missile attack
- [x] Mine stomp
- [x] Mine Seaking
- [x] Mine pattern + bullet patterns

**Stage 2**

- All of stage 1
- [ ] Bridge shake plus debris falling pattern 1
- [ ] Bridge shake plus debris falling pattern 2

**Stage 3**

- [ ] Small drone attack
- [ ] Medium drone attack
- [ ] Boss bash patterns

 **Overall**

- [ ] Put more pause moments in to make fight more fair..
- [ ] Tune amount of health of boss
