### ISSUE TITLE
Stage 1 Midstage boss

### ISSUE THREAD

**Issue by matthijsgroen** [speedlazer/speedlazer#99]
**Stage 1:**
- DroneShip sails into view with the mine launcher

**player action to advance:** Destroy missle launcher

**Stage 2:**

**Ship sails to the left...**
- Small drones come in to view to draw attention and protect missile launchers
- Missile launcher left activate 
- Hatches (1 & 2) activate and open, releasing drones 

**player action to advance:** Destroy missile launcher 

**Stage 3:**

**Ship catches you up again...**
- Hatches open again 
- Missile launcher right activates 
- Helicopter activates and flies up 
- Able to destroy cabin and hatches

**player action to advance:** Destroy missile launcher, hatches, cabin and helicopter

**Graphics**

- [x] MineCannon
- [x] Turret Base
- [x] Seperate cabin from rest of ship
- [x] Make cabins destructable
- [ ] Rocket Turret
- [ ] Update details/greeble/scale of ship

**Comment by matthijsgroen** [comment]
Ship has been redone, closing issue
